### ISSUE TITLE
Bug: Images overflowing out of screen height in gallery 

### ISSUE THREAD

**Issue by GenDelta** [codexsit/codexsit.github.io#46]
**Description of the bug**
For some images in the gallery, the button to close an image is overflowing outside the screen height and is not accessible. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://codexsit.github.io/CodeX-Website/#/gallery'
2. Click on 'the first image
3. Click on the right-hand side button to go to the next image 
4. You cannot access the button to close the image as the image is overflowing from the screen

**Expected behaviour**
The button to close the images should be accessible for each image. 

**Screenshots**
- Normal behaviour:
![image](https://github.com/codeXsit/CodeX-Website/assets/88091748/d0985f00-d04e-4578-8905-8ac4e438b9b6)
-Bug:
![image](https://github.com/codeXsit/CodeX-Website/assets/88091748/603ba03a-c8d1-4c46-8867-53ff4d6eb3b5)

**Comment by Miran-Firdausi** [comment]
Implemented
